### ISSUE TITLE
Ongoing issues

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose-wizard#1]
- [x] Glitch: In the running application, if the mouse hovers over the 'Logout' button the 'Logout' bubble extends beyond the page triggering the scroll bars to be overlaid and the button to move slightly. Similar in the wizard with the export button. If the mouse gets held in the wrong location over/not over the button the browser can 'strobe' between the two states (Edge strobes, firefox doesn't strobe).
- [x] Inconvenience: No reorder capability for pages or of variables in a settings panel. (I could probably export and edit the JSON to get around this...)
- [x] Inconvenience: The variable field doesn't align to the end of the label eg. if a panel is wide and the labels/names are all short, there is a large gap between the names and the input, and the visible area of eg. a text variable is smaller than it could be.
- [x] Bug: In the wizard, if I navigate to the 'Web UI' tab, then away from it, then back to the Web UI tab and then select a different UI page to edit, the page contents disappear and do not return. Need to refresh the page (and lose all edits). (Edge + Firefox)
- [x] Bug: After a bunch of manual editing, sometimes the Web UI tab stops responding (can't blank the page, or add a panel). Possibly the same bug as above? [THIS IS JAVASCRIPT ERROR - REPORT IT AS MENTIONED IN THE README]
- [x] Bug: If I add a variable to a settings panel, and the default variable is the one I want and I don't change it, it doesn't get added properly. The variable field shows ??? in the wizard and in the running application. If I change it to a different variable and back again it then works.
- [x] Bug: I get a build failure. Nowhere did s_vars in mongoose_impl.c get declared, nor can I find anywhere did its type (something with a .name, .type and .fn) get declared. Whether MQTT is enabled or disabled I get the same failure, including when building the default example with no changes. If I disable MQTT and remove findvar and expandvar, it builds. So I can't offer much more feedback on that presently.
- [x] Bug: If I create numerous pages, with varying authentication levels eg. Config 1 Network 2 Feature Unlock 0 Calibration 4 File Download 0,  and login with a user with an intermediate auth level 1, the correct pages are shown on the left (Config, Feature Unlock, File Download), but when I click them the wrong page is displayed, eg. if I click on File Download I am shown the Feature Unlock page. I assume the js is accessing the page by index, but the indexes change at different auth levels... The workaround is to list pages in ascending auth order
- [x] Bug: A box is displayed around the logo SVG. 
- [x] Bug: When multiple panels are created on multiple pages, adjusting the size of one panel often makes the size of all of them (across different pages) the same. Noticing this primarily when I have one settings panel per page on several pages.
- [x] Inconvenience: Logging in, pressing the 'enter' key doesn't initiate login, I need to click the 'Sign In' button with the mouse. Yes, I'm a keyboard princess.
- [x] Glitch: On the running application, if I log in as admin and navigate to the 'Admin' tab, then log out and log back in as 'user' I am returned to the admin page and can see the Secret Data panel (but the data indicates ACCESS DENIED). I would have anticipated being directed to the dashboard page on a fresh login. I also saw this once with the 'admin' panel on the dashboard appearing at user auth level but have been unable to replicate. Low criticality, no data value leakage (but leakage of data name if it's a settings type panel) and only appears immediately after an admin was logged in. Also doesn't leak anything that couldn't be found by inspecting the page code.
- [x] Inconvenience: New fields in a setting panel get added to the top instead of the bottom (counterintuitive, but maybe makes sense if there are many variables added to avoid scrolling?)

**Comment by dvosully** [comment]
- [ ] Header files should have CPP header guards so functions can be called from CPP - mongoose_glue.h specifically should have this
- [ ] Maybe mongoose_config.h should specify a value for `MG_ENABLE_POSIX_FS` now that it is used in the user code?
- [ ] In mongoose_glue.c, `glue_file_open_xxx()` wraps `fopen()` with `#if MG_ENABLE_POSIX_FS`, but `glue_file_write_xxx()` and `glue_file_close_xxx()` do not wrap the posix calls. This should be consistent. eg
```
#if MG_ENABLE_POSIX_FS
  return fclose(fp) == 0;
#else
  return true;
#endif
```
and
```
#if MG_ENABLE_POSIX_FS
  return fwrite(buf, 1, len, fp) == len;
#else
  return true;
#endif
```
- [ ] mongoose_glue.c should use explicit casts to cast pointers to permit unmodified compilation as cpp if required (eg. if hal.h or equivalent uses cpp functionality such as classes).
  Noted in `glue_file_open_xxx()`, `glue_file_write_xxx()` and `glue_file_close_xxx()` casting `fp` `(void*)` to `(FILE*)`
- [ ] Possibly not an issue, but: When an ota variable is created in the wizard, the `mg_ota_xxx()` functions must be created for the project to compile. On the ESP32 platform (and possible others where `MG_OTA_CUSTOM` is set?) these functions do not exist. It would be a convenience if stubbed out copies of these functions were placed in main.c (or glue?) to allow the project to build. Alternatively, setting `MG_OTA_NONE` instead of `MG_OTA_CUSTOM` would achieve this and prevent the compilation failure, leaving it to the user to implement the `mg_ota_xxx()` functions.
- [ ] In `mongoose_impl.c`, `mqtt_event_handler()` prints a closing message `MG_DEBUG(("%lu Closing"));` with no supplied parameter. This should have a parameter as follows: `MG_DEBUG(("%lu Closing", c->id));`
- [ ] Generating (or subscribing to?) the mqtt rx topic crashes the application with a corrupted backtrace if the rx topic contains an variable whose value is not empty. To duplicate: Enable MQTT in the wizard and build the default project. Optionally adjust the device_id default value to be an empty string to observe a successful connection instead. Observed on ESP32.
- [ ] When an action/button is placed on a panel which has a save button, clicking the 'save' button triggers the action. I believe the button should _only_ be triggered if it is clicked or otherwise explicitly activated.
- [ ] When a file is uploaded using the upload type, once the file finishes uploading, the file being written to is not closed until the socket times out. I believe mongoose_impl.c should set the 'is_draining' parameter once the upload is complete to immediately close the socket and file, as shown below:
```
  // Catch uploaded file data for both MG_EV_READ and MG_EV_HTTP_HDRS
  if (us->marker == 'U' && (ev == MG_EV_HTTP_HDRS || ev == MG_EV_READ) &&
      us->expected > 0 && c->recv.len > 0) {
    bool ok = us->fn_write(us->fp, c->recv.buf, c->recv.len);
    us->received += c->recv.len;
    MG_DEBUG(("%lu chunk: %lu bytes, %lu so far, %lu total, ok: %d", c->id,
              c->recv.len, us->received, us->expected, ok));
    c->recv.len = 0;  // Delete received data
    if (ok == false) {
      mg_http_reply(c, 400, "", "Upload error\n");
      c->is_draining = 1;  // Close connection when response it sent
    } else if (us->received >= us->expected) {
      // Uploaded everything. Send response back
      MG_INFO(("%lu done, %lu bytes", c->id, us->received));
      mg_http_reply(c, 200, NULL, "%lu ok\n", us->received);
      c->is_draining = 1;  // Close connection when response is sent <<< ADD THIS LINE
    }
  }
```
- [ ] Uploading a file to a file variable endpoint when not authenticated causes the application to crash in mongoose_impl.c handle_uploads(). To duplicate: create and place a file variable with a write auth level of 1, log in to the dashboard as user, restart the mongoose application, then try to upload a file using the (invalidated) user session open in the browser.
- [ ] A callback to create/initialise the mqtt semaphore should possibly be added. In many RTOSes, a semaphore must be created/initialised at runtime before it can be used. A glue_lock_create() function in mongoose_glue.c and called early in mongoose_impl.c mongoose_init() would probably do (though initialising the semaphore earlier in the runtime might be wiser, in which case it would need to be a user problem after all... having a glue_lock_create() function would still be good though)

**Comment by dvosully** [comment]
- [ ] Dropdowns are completely broken in the current wizard release. When adding a dropdown variable to a panel, the 'list' variables are unavailable to select to populate the dropdown. This can be observed on the default web UI builder panel, Settings > Log Level variable.

**Comment by dvosully** [comment]
- [ ] Toggles in panels with a 'save' button don't send a POST to the server (either when clicked, or when save is clicked). Expected behaviour: State of a toggle is sent when 'save' is clicked.
