### ISSUE TITLE
Imrpove MQTT handling

### ISSUE THREAD

**Issue by cpq** [cesanta/mongoose-wizard#15]
> Sending an MQTT message at QoS1. To do this I need:
> To be able to receive the MG_EV_MQTT_CMD event in my code
> To get the message ID of the sent message
> To be able to set the attributes of a published message (at minimum this requires: qos, retransmit_id)
> Using mutual authentication (or TLS at all) for MQTT (eg. connecting to AWS IoT MQTT)
> Doing this requires a new glue callback to set the mg_tls_opts parameters, called when handling the MG_EV_CONNECT callback.

@dvosully  Could you clarify, what is the use case for message / retransmit ID ?

**Comment by dvosully** [comment]
The retransmit ID must be populated when resending an MQTT message at QoS1 or QoS2.

**Comment by cpq** [comment]
Thanks. Can you share a relevant snippet that you've added to the mongoose_impl.c , please?

**Comment by dvosully** [comment]
In mongoose_impl.c I added the following to mqtt_event_handler():
```
  } else if (ev == MG_EV_MQTT_CMD) {
    glue_mqtt_cmd_received((struct mg_mqtt_message *)ev_data);
  }
```
With this new `glue_mqtt_cmd_received()` callback my user code can track whether a message has been ACKed, by getting the command type and the message ID it correlates to (if any).

Then I have modified `glue_mqtt_publish()` so I populate the options struct in user code, and so it returns the message ID. The modified version looks like so:
```
uint16_t glue_mqtt_publish(struct mg_mqtt_opts *opts) {
  uint16_t id = 0;
  glue_lock();
  if (s_mqtt_conn != NULL) id = mg_mqtt_pub(s_mqtt_conn, opts);
  glue_unlock();
  return id;
}
```
The glue function is still useful for handling the `glue_lock()` and `glue_unlock()`, as well as having access to the s_mqtt_conn variable which is not accessible in mongoose_glue.c

Alternatively it could be done by adding more arguments to glue_mqtt_publish eg.
```
uint16_t glue_mqtt_publish(const char* topic, const char* msg, size_t len, int qos, uint16_t retransmit_id) ...
```
but I felt it was cleaner to just let the user code populate the options struct instead.

The above changes are sufficient for implementing QoS1 (I am sure they are sufficient for QoS2 but I haven't actually done that).

**Comment by dvosully** [comment]
Regarding cert/key files for MQTT two-way auth, I would be keen for the API to maintain some way for user code to supply these if required, rather than embedding them into mongoose_fs.c and mongoose_impl.c - that would be problematic for any application where these get generated and loaded into the device by the end user.

CA file is a bit different, because a generic list of CA certs can cover most public servers pretty easily.

The changes I have made to implement TLS with (optional) two-way auth are:
In mongoose_impl.c mqtt_event_handler() add:
```
  } else if (ev == MG_EV_CONNECT) {
    struct mg_tls_opts opts = {0};
    if(glue_mqtt_tls_opts(&opts)) {
      MG_DEBUG(("%lu TLS init", c->id));
      mg_tls_init(c, &opts);
    }
  }
```
and move the previous contents of MG_EV_CONNECT into MG_EV_MQTT_OPEN instead.

A default glue_mqtt_tls_opts() in mongoose_glue.c could look like:
```
bool glue_mqtt_tls_opts(struct mg_tls_opts* opts) {
  opts->name = mg_url_host(WIZARD_MQTT_URL);
  opts->ca = mg_unpacked("/certs/ca.pem");
  //opts->cert = mg_unpacked("/certs/cert.pem");
  //opts->key = mg_unpacked("/certs/key.pem");
  opts->skip_verification = false;

  return mg_url_is_ssl(WIZARD_MQTT_URL);
}
```
But I think it's pretty important to keep the population of the mg_tls_opts in mongoose_glue.c so the user code can supply authentication parameters that may not be known at compile time.
The mg_url_is_ssl test could be done in mongoose_impl.c, but that would remove the option from user code to select TLS if the protocol (mqtt/mqtts) wasn't set explicitly.

(Getting further off topic, handling username/password authentication as required by private HiveMQ brokers, instead of certificate/key will require a whole other handler I haven't thought about. Off the top of my head, it requires TLS without cert or key (achieved by the above code) and then the username/password get supplied somewhere in the MG_EV_MQTT_OPEN handler IIRC. I don't need that immediately but want to include support for it eventually in case an end user is using a private HiveMQ broker instead of AWS.)

**Comment by cpq** [comment]
@dvosully awesome, thank you! work is in progress..

**Comment by cpq** [comment]
@dvosully MQTT glue API has changed significantly: pretty much all control is given to the glue code.
It can init TLS, can subscribe to anything, and publish to anything using `mg_*` API.
`mongoose_impl.c` has only a simple event handler which calls out to glue, and a reconnection timer.

Note: If user code decides to publish from a different thread, it should lock/unlock

For now, all certificate handling is expected to be done by the user code.
Soon, we'll just include a default `ca.pem` for the convenience - so that glue code could use either that default, or use its own CA.

Please test and feedback.

**Comment by dvosully** [comment]
Thanks Sergey,
I have tested this update and it is working well. This update has enabled most of the above capabilities to be implemented in glue without modifications to `mongoose_impl.c`

Ordinary TLS authentication works, as well as mutual authentication.
I can also see that username/password authentication will be able to be handled in glue now that the MQTT open event callback is handled in glue (I have not yet implemented this, but the required options can be set in the connect callback).
I have been able to implement RPC in glue, including with delay callbacks.
I have also been able to implement my own protocol handler in glue now that the mg_mgr is available.

The only thing that would be required to close this would be to add a callback on the MG_EV_MQTT_CMD event to allow user code to catch MQTT CMD messages so that message delivery state can be monitored for QoS1 and 2.
The following handler in mqtt_event_handler() in `mongoose_impl.c` would suffice for this:
```
  } else if (ev == MG_EV_MQTT_CMD) {
    glue_mqtt_on_cmd((struct mg_mqtt_message *)ev_data);
  }
```
The instantiation could be empty:
```
void glue_mqtt_on_cmd(struct mg_mqtt_message *mm) {
}
```
The eventual addition of a default `ca.pem` will be a nice convenience to round this out.

Some minor code feedback:
I believe that the following lines in `mongoose_glue.h` should be protected by `#if WIZARD_ENABLE_MQTT` as the instantiations in `mongoose_glue.c` are conditional on that.
```
extern struct mg_connection *g_mqtt_conn;  // MQTT client connection

void glue_mqtt_tls_init(struct mg_connection *c);
void glue_mqtt_on_connect(struct mg_connection *c, int code);
void glue_mqtt_on_message(struct mg_connection *c, struct mg_str topic,
                          struct mg_str data);
```

**Comment by cpq** [comment]
@dvosully Thank you! Added `glue_mqtt_on_cmd()`. 

There is no need for the `#ifdef` quards, as the code is not added at all if MQTT is not enabled.
W.r.t. adding custom handlers: added `glue_init()` which is called at the end of `mongoose_init()`

Is there anything else pending for the MQTT case?

**Comment by dvosully** [comment]
Wonderful! The `glue_init()` will be helpful, good thinking.

With `glue_mqtt_on_cmd()` added that supports every use case and connection type I can think of for MQTT. Good to close IMO.
